package me.kp56.timetables;

import me.kp56.timetables.configuration.Config;
import me.kp56.timetables.timetable.Runner;
import me.kp56.timetables.timetable.Student;
import me.kp56.timetables.timetable.Timetable;
import me.kp56.timetables.ui.UI;

import java.io.File;
import java.io.IOException;
import java.util.*;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicReference;

public class Main {
    private static Config config = Config.getInstance();
    private static File workingDir = new File(System.getProperty("user.dir"));

    public static void main(String[] args) throws InterruptedException {
        Student.students.add(new Student("Avcioglu Aylin", List.of(Timetable.Subject.MATH_AA_SL, Timetable.Subject.ENGLISH_A_HL, Timetable.Subject.ECONOMICS_SL, Timetable.Subject.BIOLOGY_HL, Timetable.Subject.CHEMISTRY_HL, Timetable.Subject.POLISH_NO_EXAMINATION, Timetable.Subject.DSD, Timetable.Subject.FRENCH_B_SL, Timetable.Subject.TOK, Timetable.Subject.Z_WYCH)));
        Student.students.add(new Student("Bartkowska Aleksandra", List.of(Timetable.Subject.GEOGRAPHY_HL, Timetable.Subject.ENGLISH_A_HL, Timetable.Subject.ECONOMICS_HL, Timetable.Subject.CHEMISTRY_SL, Timetable.Subject.MATH_AI_SL, Timetable.Subject.POLISH_NO_EXAMINATION, Timetable.Subject.DSD, Timetable.Subject.FRENCH_B_SL, Timetable.Subject.TOK, Timetable.Subject.Z_WYCH)));
        Student.students.add(new Student("Bryl Zofia", List.of(Timetable.Subject.MATH_AA_SL, Timetable.Subject.POLISH_A_SL, Timetable.Subject.ENGLISH_B_HL, Timetable.Subject.SPANISH_B_HL, Timetable.Subject.BIOLOGY_HL, Timetable.Subject.CHEMISTRY_HL, Timetable.Subject.DSD, Timetable.Subject.TOK, Timetable.Subject.Z_WYCH)));
        Student.students.add(new Student("Chmielewski Oskar", List.of(Timetable.Subject.MATH_AA_HL, Timetable.Subject.PHYSICS_HL, Timetable.Subject.POLISH_A_SL, Timetable.Subject.ENGLISH_B_HL, Timetable.Subject.ECONOMICS_SL, Timetable.Subject.CHEMISTRY_SL, Timetable.Subject.DSD, Timetable.Subject.TOK, Timetable.Subject.Z_WYCH)));
        Student.students.add(new Student("Dolata Antoni", List.of(Timetable.Subject.MATH_AA_HL, Timetable.Subject.POLISH_A_SL, Timetable.Subject.ENGLISH_B_HL, Timetable.Subject.ECONOMICS_HL, Timetable.Subject.GERMAN_B_HL, Timetable.Subject.CHEMISTRY_SL, Timetable.Subject.DSD, Timetable.Subject.TOK, Timetable.Subject.Z_WYCH)));
        Student.students.add(new Student("Drgas Kalina", List.of(Timetable.Subject.POLISH_A_SL, Timetable.Subject.ENGLISH_B_HL, Timetable.Subject.BIOLOGY_HL, Timetable.Subject.CHEMISTRY_HL, Timetable.Subject.MATH_AI_SL, Timetable.Subject.DSD, Timetable.Subject.FRENCH_B_SL, Timetable.Subject.TOK, Timetable.Subject.Z_WYCH)));
        Student.students.add(new Student("Flicińska Zuzanna", List.of(Timetable.Subject.MATH_AA_SL, Timetable.Subject.POLISH_A_HL, Timetable.Subject.ENGLISH_A_HL, Timetable.Subject.SPANISH_B_HL, Timetable.Subject.BIOLOGY_SL, Timetable.Subject.HISTORY_HL, Timetable.Subject.DSD, Timetable.Subject.TOK, Timetable.Subject.Z_WYCH)));
        Student.students.add(new Student("Fliegner Szymon", List.of(Timetable.Subject.MATH_AA_HL, Timetable.Subject.PHYSICS_HL, Timetable.Subject.ENGLISH_A_SL, Timetable.Subject.ECONOMICS_SL, Timetable.Subject.GERMAN_B_HL, Timetable.Subject.CHEMISTRY_HL, Timetable.Subject.POLISH_NO_EXAMINATION, Timetable.Subject.DSD, Timetable.Subject.TOK, Timetable.Subject.Z_WYCH)));
        Student.students.add(new Student("Grzesiak Kornelia", List.of(Timetable.Subject.MATH_AA_SL, Timetable.Subject.ENGLISH_A_HL, Timetable.Subject.ECONOMICS_SL, Timetable.Subject.GERMAN_B_HL, Timetable.Subject.BIOLOGY_HL, Timetable.Subject.CHEMISTRY_HL, Timetable.Subject.POLISH_NO_EXAMINATION, Timetable.Subject.DSD, Timetable.Subject.TOK, Timetable.Subject.Z_WYCH)));
        Student.students.add(new Student("Grzeszczyk Maja", List.of(Timetable.Subject.MATH_AA_SL, Timetable.Subject.ENGLISH_A_SL, Timetable.Subject.ECONOMICS_SL, Timetable.Subject.GERMAN_B_HL, Timetable.Subject.BIOLOGY_HL, Timetable.Subject.CHEMISTRY_HL, Timetable.Subject.POLISH_NO_EXAMINATION, Timetable.Subject.DSD, Timetable.Subject.TOK, Timetable.Subject.Z_WYCH)));
        Student.students.add(new Student("Jeleń Zuzanna", List.of(Timetable.Subject.MATH_AA_SL, Timetable.Subject.POLISH_A_SL, Timetable.Subject.ENGLISH_A_HL, Timetable.Subject.SPANISH_B_HL, Timetable.Subject.BIOLOGY_HL, Timetable.Subject.CHEMISTRY_HL, Timetable.Subject.DSD, Timetable.Subject.TOK, Timetable.Subject.Z_WYCH)));
        Student.students.add(new Student("Kasperkiewicz Marianna", List.of(Timetable.Subject.POLISH_A_SL, Timetable.Subject.ENGLISH_A_HL, Timetable.Subject.BIOLOGY_HL, Timetable.Subject.CHEMISTRY_HL, Timetable.Subject.MATH_AI_SL, Timetable.Subject.DSD, Timetable.Subject.FRENCH_B_SL, Timetable.Subject.TOK, Timetable.Subject.Z_WYCH)));
        Student.students.add(new Student("Kraiz Malek", List.of(Timetable.Subject.MATH_AA_SL, Timetable.Subject.POLISH_A_SL, Timetable.Subject.ENGLISH_B_HL, Timetable.Subject.ECONOMICS_SL, Timetable.Subject.BIOLOGY_HL, Timetable.Subject.CHEMISTRY_HL, Timetable.Subject.DSD, Timetable.Subject.TOK, Timetable.Subject.Z_WYCH)));
        Student.students.add(new Student("Kubaszewska Franciszka", List.of(Timetable.Subject.MATH_AA_SL, Timetable.Subject.POLISH_A_SL, Timetable.Subject.ENGLISH_A_HL, Timetable.Subject.SPANISH_B_HL, Timetable.Subject.BIOLOGY_HL, Timetable.Subject.CHEMISTRY_HL, Timetable.Subject.DSD, Timetable.Subject.TOK, Timetable.Subject.Z_WYCH)));
        Student.students.add(new Student("Kubecki Mikołaj", List.of(Timetable.Subject.MATH_AA_SL, Timetable.Subject.POLISH_A_SL, Timetable.Subject.ENGLISH_A_SL, Timetable.Subject.ECONOMICS_HL, Timetable.Subject.BIOLOGY_HL, Timetable.Subject.CHEMISTRY_HL, Timetable.Subject.DSD, Timetable.Subject.TOK, Timetable.Subject.Z_WYCH)));
        Student.students.add(new Student("Kusiak Marta", List.of(Timetable.Subject.MATH_AA_HL, Timetable.Subject.POLISH_A_SL, Timetable.Subject.ENGLISH_B_HL, Timetable.Subject.ECONOMICS_SL, Timetable.Subject.GERMAN_B_HL, Timetable.Subject.CHEMISTRY_HL, Timetable.Subject.DSD, Timetable.Subject.TOK, Timetable.Subject.Z_WYCH)));
        Student.students.add(new Student("Lisek Karina", List.of(Timetable.Subject.MATH_AA_SL, Timetable.Subject.PHYSICS_HL, Timetable.Subject.ENGLISH_A_HL, Timetable.Subject.COMPUTER_SCIENCE_HL, Timetable.Subject.HISTORY_HL, Timetable.Subject.POLISH_NO_EXAMINATION, Timetable.Subject.DSD, Timetable.Subject.FRENCH_B_SL, Timetable.Subject.TOK, Timetable.Subject.Z_WYCH)));
        Student.students.add(new Student("Marek Adam", List.of(Timetable.Subject.MATH_AA_HL, Timetable.Subject.POLISH_A_SL, Timetable.Subject.ENGLISH_B_HL, Timetable.Subject.SPANISH_B_HL, Timetable.Subject.ECONOMICS_SL, Timetable.Subject.COMPUTER_SCIENCE_HL, Timetable.Subject.DSD, Timetable.Subject.TOK, Timetable.Subject.Z_WYCH)));
        Student.students.add(new Student("Matuszczak Maciej", List.of(Timetable.Subject.MATH_AA_HL, Timetable.Subject.ENGLISH_A_SL, Timetable.Subject.ECONOMICS_SL, Timetable.Subject.GERMAN_B_HL, Timetable.Subject.BIOLOGY_HL, Timetable.Subject.CHEMISTRY_HL, Timetable.Subject.POLISH_NO_EXAMINATION, Timetable.Subject.DSD, Timetable.Subject.TOK, Timetable.Subject.Z_WYCH)));
        Student.students.add(new Student("Michalczuk Emilia", List.of(Timetable.Subject.POLISH_A_SL, Timetable.Subject.ENGLISH_A_HL, Timetable.Subject.SPANISH_B_HL, Timetable.Subject.BIOLOGY_SL, Timetable.Subject.HISTORY_HL, Timetable.Subject.MATH_AI_SL, Timetable.Subject.DSD, Timetable.Subject.TOK, Timetable.Subject.Z_WYCH)));
        Student.students.add(new Student("Paszkowska Zuzanna", List.of(Timetable.Subject.ENGLISH_A_HL, Timetable.Subject.SPANISH_B_HL, Timetable.Subject.ECONOMICS_SL, Timetable.Subject.GERMAN_B_HL, Timetable.Subject.BIOLOGY_SL, Timetable.Subject.MATH_AI_SL, Timetable.Subject.POLISH_NO_EXAMINATION, Timetable.Subject.DSD, Timetable.Subject.TOK, Timetable.Subject.Z_WYCH)));
        Student.students.add(new Student("Piotrowska Milena", List.of(Timetable.Subject.POLISH_A_SL, Timetable.Subject.ENGLISH_A_HL, Timetable.Subject.ECONOMICS_HL, Timetable.Subject.COMPUTER_SCIENCE_SL, Timetable.Subject.HISTORY_HL, Timetable.Subject.MATH_AI_SL, Timetable.Subject.DSD, Timetable.Subject.TOK, Timetable.Subject.Z_WYCH)));
        Student.students.add(new Student("Raźnikiewicz Dawid", List.of(Timetable.Subject.MATH_AA_SL, Timetable.Subject.ENGLISH_A_HL, Timetable.Subject.ECONOMICS_HL, Timetable.Subject.COMPUTER_SCIENCE_SL, Timetable.Subject.GERMAN_B_HL, Timetable.Subject.HISTORY_HL, Timetable.Subject.POLISH_NO_EXAMINATION, Timetable.Subject.DSD, Timetable.Subject.TOK, Timetable.Subject.Z_WYCH)));
        Student.students.add(new Student("Reshetnyk Diana", List.of(Timetable.Subject.MATH_AA_SL, Timetable.Subject.POLISH_A_SL, Timetable.Subject.GEOGRAPHY_HL, Timetable.Subject.ENGLISH_B_HL, Timetable.Subject.ECONOMICS_HL, Timetable.Subject.COMPUTER_SCIENCE_SL, Timetable.Subject.DSD, Timetable.Subject.TOK, Timetable.Subject.Z_WYCH)));
        Student.students.add(new Student("Sadowczyk Milena", List.of(Timetable.Subject.GEOGRAPHY_HL, Timetable.Subject.ENGLISH_A_HL, Timetable.Subject.BIOLOGY_HL, Timetable.Subject.CHEMISTRY_HL, Timetable.Subject.MATH_AI_SL, Timetable.Subject.POLISH_NO_EXAMINATION, Timetable.Subject.DSD, Timetable.Subject.FRENCH_B_SL, Timetable.Subject.TOK, Timetable.Subject.Z_WYCH)));
        Student.students.add(new Student("Seite-Jastrzębska Adrianna", List.of(Timetable.Subject.POLISH_A_HL, Timetable.Subject.ENGLISH_A_HL, Timetable.Subject.GERMAN_B_HL, Timetable.Subject.BIOLOGY_SL, Timetable.Subject.HISTORY_HL, Timetable.Subject.MATH_AI_SL, Timetable.Subject.DSD, Timetable.Subject.TOK, Timetable.Subject.Z_WYCH)));
        Student.students.add(new Student("Verschelden Julia", List.of(Timetable.Subject.MATH_AA_SL, Timetable.Subject.PHYSICS_HL, Timetable.Subject.ENGLISH_A_HL, Timetable.Subject.COMPUTER_SCIENCE_SL, Timetable.Subject.HISTORY_HL, Timetable.Subject.POLISH_NO_EXAMINATION, Timetable.Subject.DSD, Timetable.Subject.FRENCH_B_SL, Timetable.Subject.TOK, Timetable.Subject.Z_WYCH)));
        Student.students.add(new Student("Ziółkowski Hubert", List.of(Timetable.Subject.MATH_AA_SL, Timetable.Subject.PHYSICS_HL, Timetable.Subject.POLISH_A_SL, Timetable.Subject.ENGLISH_B_HL, Timetable.Subject.BIOLOGY_HL, Timetable.Subject.CHEMISTRY_HL, Timetable.Subject.DSD, Timetable.Subject.TOK, Timetable.Subject.Z_WYCH)));
        UI ui = new UI();
    }
}
